use_frameworks!

target 'ResourceTest_Example' do
  pod 'ResourceTest', :path => '../'

  target 'ResourceTest_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
